version: "3.7"
services:
  lms: &lms
    build:
      context: .
      dockerfile: ./docker-files/Dockerfile
    image: lms:latest
    command: sh -c "./docker-files/start"

  api_tests:
    << : *lms
    environment:
      - service_url=http://lms:8000
    depends_on:
      - lms
    volumes:
      - ${WORKSPACE}/api_tests/reports:/app/reports
    command: sh -c "rm -rf pytest.ini && sleep 5 && python -m pytest library/api_tests --html=reports/api_test_report.html --self-contained-html"
