version: "3"
services:
  lms:
    build:
      context: .
      dockerfile: ./docker-files/Dockerfile
    image: lms:0.1
    volumes:
      - ${WORKSPACE}/reports/unit_tests:/app/reports
    command: ./docker-files/unit_test
